### ISSUE TITLE
getting customer attributes?

### ISSUE THREAD

**Issue by Pomax** [customerio/customerio-node#125]
I was wondering how to get the equivalent of calling `https://track.customer.io/api/v1/customers/${userId}/attributes` using this library. https://www.customer.io/docs/api/#operation/getPersonAttributes shows an example with the plain https module, but that seems a little silly if there's an API package available? =)

**Comment by mike-engel** [comment]
Hi @Pomax, right now we don't have a method in the library to access that endpoint. You could need to make a manual https request to that endpoint to receive that data. If you would like to add it to this library, we're open to pull requests! Otherwise, I can't guarantee when it will be added to this library.

**Comment by Pomax** [comment]
In that case you probably want to keep this open with a "help wanted" so folks can see there's something they might be able to help out on =)
