### ISSUE TITLE
Removal of manual segments APIs

### ISSUE THREAD

**Issue by yjwong** [customerio/customerio-node#38]
Hi there, I observed that the manual segment APIs `addToSegment` and `removeFromSegment` were removed in this commit and no longer exists in the v1.0.0 release: https://github.com/customerio/customerio-node/commit/e487c3c33e7fbbb77c502b1c0def1137f56f2a16

Is there any reason why these APIs were removed? We currently make use of these APIs.

**Comment by mike-engel** [comment]
Hi @yjwong, thanks for your patience on this issue.

We recently [deprecated the APIs](https://customer.io/docs/api/#operation/add_to_segment) to add and remove people from manual segments. They still work for now, but with the release of 1.0.0 and the transactional message feature, we decided to remove those functions from all of our client libraries.

If you need to continue using them but use the latest version of `customerio-node`, you will have to make the HTTP request manually as defined in our [API documentation](https://customer.io/docs/api/#operation/add_to_segment).

Eventually we plan to move them from the Track API to our App or Beta API because that's a much better fit for the purpose of these two API methods.

I'm sorry for any trouble this has caused, and if you have more questions, please let us know!
