### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by bobbypriambodo** [customerio/customerio-node#9]
Hi, I've been meaning to send data from my Node.js app to Customer.io, and stumbled upon this official package. The API looks complete, but it lacks traction compared to other unofficial libraries (such as [node-customerio](https://www.npmjs.com/package/node-customerio) or [node-customer.io](https://www.npmjs.com/package/node-customer.io)).

Will this library be supported in the long run if I decided to use this in production or should I use the other libraries?

**Comment by joepurdy** [comment]
Hey @bobbypriambodo! Because this is our official Customer.io Node library we'll continue providing updates to it as needed to support integrating with Customer.io.

In the past we haven't performed many updates due to the fact that the Customer.io API hasn't undergone significant changes requiring updates to client libraries such as this one. Recently we did add a new API method for triggered broadcasts which has landed in the Node.js library in v0.3.0.

Plenty of our customers use the Node.js library for their production Customer.io integrations so as to whether or not it's "production ready" we'd have to say yes. 😃
